# Copyright Vcnngr
# Based on Bitnami work - Copyright Broadcom, Inc.
# SPDX-License-Identifier: APACHE-2.0

services:
  apache:
    image: docker.io/vcnngr/apache:2.4
    ports:
      - 80:8080
      - 443:8443
